### ISSUE TITLE
Failure tracking summary 

### ISSUE THREAD

**Issue by gkalpak** [angular/ngcc-validation#386]
Given that many failures fall under the same root causes, I think it makes sense (at least it helps me :grin:) to have a summary of the failures grouped by root cause. This is what this is issue is for.

For completeness, related info is also captured [here](https://docs.google.com/spreadsheets/d/1TEawfLbWQjqTDst2Jrm2KF6udMVMjuKiz8LG4NPD7WQ) and [there](https://docs.google.com/spreadsheets/d/1brJHrqGYGGD4HRsFudGW6CynHHX34Zf8H31qD7wjPac).

<sub>_Last update: 2019-11-06_</sub>

---

## 1. With pending PR to fix

_Projects that are currently failing, but for which there is a pending PR to fix them._

- [x] **alfrescoadf-core-ngcc**: Alfresco/alfresco-ng2-components#5153

## 2. Transitive failures

_Projects that are failing due to some of their dependencies' failing and those dependencies also happen to have their own project in this repo._

- [x] **nebularauth-ngcc**: Failing dep: `@nebular/theme` (project: `nebulartheme-ngcc`) (fixed by angular/angular#33264, #466)
- [x] **nebulardate-fns-ngcc**: Failing dep `@nebular/theme` (project: `nebulartheme-ngcc`) (fixed by angular/angular#33264, #466)
- [x] **nebulareva-icons-ngcc**: Failing dep: `@nebular/theme` (project: `nebulartheme-ngcc`) (fixed by angular/angular#33264, #466)
- [x] **nebularmoment-ngcc**: Failing dep: `@nebular/theme` (project: `nebulartheme-ngcc`) (fixed by angular/angular#33264, #466)
- [x] **ngx-chips-ngcc**: Failing dep: `ng2-material-dropdown` (project: `ng2-material-dropdown-ngcc`) (fixed by #400)

## 3. Importing removed `Renderer`

_Projects that are failing, because they try to import `Renderer`, which is removed in v9. This is a v9 breaking change - not `ngcc`-specific._

- [ ] **angular-froala-wysiwyg-ngcc** (fix froala/angular-froala-wysiwyg#349, issue froala/angular-froala-wysiwyg#347)
- [x] **angular-tree-component-ngcc** (fixed by #521)
- [x] **mobx-angular-ngcc** (mobxjs/mobx-angular#93)
- [ ] **mydatepicker-ngcc** (kekeh/mydatepicker#624)
- [ ] **ng2-completer-ngcc** (oferh/ng2-completer#437)
- [x] **ng2-material-dropdown-ngcc** (Gbuomprisco/ng2-material-dropdown#66) (fixed by #399)

## 4. Missing type argument in `ngBaseDef`

_Projects that are failing, because of missing type arguments in the generated `ngBaseDef` declaration. `ngBaseDef` will soon go away in `ngtsc` and be replaced by `ngDirectiveDef`. (We should make sure that the problem is fixed then.)_

- [x] **delonform-ngcc**: "Generic type 'Widget<T, UIT>' requires 2 type argument(s)" (fixed by angular/angular#33264, #466)
- [x] **nebulartheme-ngcc**: "Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s)" (fixed by angular/angular#33264, #466)
- [x] **ng-pick-datetime-ngcc** : "Generic type 'OwlDateTime<T>' requires 1 type argument(s)" (fixed by angular/angular#33264, #466)

## 5. Failed to reflect on node

_Projects that are failing due to failing to find the exported name of a node (due to not using the `ReflectionHost` when we should). This is tracked in [FW-1508](https://angular-team.atlassian.net/browse/FW-1508). More details in #57._

- [ ] **angularx-social-login-ngcc** (abacritt/angularx-social-login#229)

## 6. Not resolved to `NgModule` class

_Projects that are failing with the following error:  
`Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class`_

- [ ] **carbonicons-angular-ngcc**
- [x] **ng2-file-upload-ngcc** (Potentially related: #284, valor-software/ng2-file-upload#1107) (fixed by #451)

## 7. Can't resolve `fs`

_Haven't looked into this one yet, but these projects are failing with the same error:  
`Module not found: Error: Can't resolve 'fs' in '.../__ivy_ngcc__/fesm5'`_

- [x] **nguniversalaspnetcore-engine-ngcc** (fixed by #388)
- [x] **nguniversalexpress-engine-ngcc** (fixed by #388)

## 8. Runtime errors

_Projects that are failing due to errors at runtime, despite the build having completed successfully._

- [x] **ng-bootstrapng-bootstrap-ngcc**: "Error: It looks like your application or one of its depen…gular/localize/init';` to your polyfills.ts file)" (fixed by #441)
- [x] **ng2-dragula-ngcc**: "ReferenceError: global is not defined" (fixed by #430)
- [ ] **ng6-breadcrumbs-ngcc**: "ReferenceError: exports is not defined" (angular/angular#33297)
    _Probably not worth supporting this one._
- [x] **ngx-formlymaterial-ngcc**: "TypeError: Cannot set property 'ɵfac' of undefined" (fixed by angular/angular#33533, #522)
- [ ] **ngx-simple-modal-ngcc**: "ReferenceError: exports is not defined" (will be fixed by #475 and/or KevCJones/ngx-simple-modal#61)
- [ ] **uirouterangular-ngcc**: "TypeError: Cannot read property 'createComponent' of undefined" (angular/angular#32166, https://github.com/ui-router/angular/issues/516#issuecomment-539767843)

## 9. Other causes

_Projects that are failing for other reasons (I haven't looked into yet). (See failure errors below for more info.)_

- [ ] **covalentcore-ngcc**: "Tried to overwrite X.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed"
- [ ] **harborui-ngcc**: "The target entry-point "@harbor/ui" has missing dependencies: @nguniversal/express-engine/tokens"
- [ ] **kendo-ui-ngcc**: "Unsupported binary operator: InKeyword" (Related: angular/angular#33453)
- [x] **mobx-angular-ngcc**: "TypeError: Cannot read property 'component' of undefined" (fixed by mobxjs/mobx-angular#94, #513) 
- [ ] **nativescript-angular-ngcc**: Tries to import `ɵDomAdapter`.
- [ ] **uirouterangular-hybrid-ngcc**: "ERROR in Symbol UIRouterModule declared in /home/circleci/repo/node_modules/@uirouter/angular/lib/uiRouterNgModule.d.ts is not exported from @uirouter/angular-hybrid (import into /home/circleci/repo/projects/uirouterangular-hybrid-ngcc/src/app/child.module.ts)" (angular/angular#32166, [FW-1652](https://angular-team.atlassian.net/browse/FW-1652))(fixed by angular/angular#33495?)

## 10. Other reported failures (not necessarily part of `ngcc-validation`)

_Packages that have been reported to be failing in Ivy, but are currently not tested against in this repo. Listing them here to have a single point of reference for known Ivy/`ngcc` failures._

- [ ] **@grapecity/wijmo.angular2.all**
- [ ] **@momentum-ui/angular** (#374)
- [ ] **@swimlane/ngx-charts** (angular/angular#30512, #497) (fixed by angular/angular#33555?)
- [ ] **@syncfusion/ej2-angular-grids** (angular/angular#30818)
- [x] **devextreme-angular** (angular/angular#31311, angular/ngcc-validation#492)
- [ ] **ion2-calendar** (angular/angular#33153)
- [x] **ng2-charts** (angular/angular#32748)
- [ ] **ng2-device-detector**/**ngx-device-detector** failing due to **ngx-highlightjs** (angular/angular#31616)
- [ ] **ng2-pdfjs-viewer** (angular/angular#31629)
- [ ] **ngx-auth-firebaseui**
- [ ] **ngx-segment-analytics** (angular/angular#31912)
- [x] **ngx-socket-io** (angular/angular#32242): Seems to work with latest version. (Verified manually by Pete; hard to write e2e test due to Socket server requirement.)
- [ ] **primeng** (angular/angular#30565)

---

<details>
  <summary>Failure error messages at the time of writing. (click to expand)</summary>

## alfrescoadf-core-ngcc
```sh
Compiling @alfresco/adf-core : module as esm5

ERROR in ../../node_modules/@alfresco/adf-core/login/components/login.component.d.ts:140:40 -
  error TS2307: Cannot find module '@angular/platform-browser/src/security/dom_sanitization_service'.

140     getBackgroundUrlImageUrl(): import("@angular/platform-browser/src/security/dom_sanitization_service").SafeStyle;
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## angular-froala-wysiwyg-ngcc
```sh
Compiling angular-froala-wysiwyg : module as esm5

ERROR in ../../node_modules/angular-froala-wysiwyg/view/view.directive.d.ts:1:22 -
  error TS2724: Module '"../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ElementRef, Renderer } from '@angular/core';
                       ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5502:31
    5502 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```

## angular-tree-component-ngcc
```sh
Compiling mobx-angular : module as esm5

ERROR in ../../node_modules/angular-tree-component/node_modules/mobx-angular/dist/directives/mobx-autorun-sync.directive.d.ts:1:41 -
  error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ViewContainerRef, TemplateRef, Renderer } from '@angular/core';
                                          ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

../../node_modules/angular-tree-component/node_modules/mobx-angular/dist/directives/mobx-autorun.directive.d.ts:1:41 -
  error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ViewContainerRef, TemplateRef, Renderer, OnInit, OnDestroy } from '@angular/core';
                                          ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

../../node_modules/angular-tree-component/node_modules/mobx-angular/dist/directives/mobx-reaction.directive.d.ts:1:41 -
  error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ViewContainerRef, TemplateRef, Renderer } from '@angular/core';
                                          ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```

## angularx-social-login-ngcc
```sh
Compiling angularx-social-login : module as esm5

ERROR in Failed to find exported name of node (CommonModule = /** @class */ (function () {
    function CommonModule() {
    }
    CommonModule = __decorate([
        NgModule({
            declarations: [COMMON_DIRECTIVES, COMMON_PIPES],
            exports: [COMMON_DIRECTIVES, COMMON_PIPES],
            providers: [
                { provide: NgLocalization, useClass: NgLocaleLocalization },
            ],
        })
    ], CommonModule);
    return CommonModule;
}())) in '/home/circleci/repo/node_modules/angularx-social-login/angularx-social-login.es5.js'.
```

## carbonicons-angular-ngcc
```sh
ERROR in ../../node_modules/@carbon/icons-angular/lib/download/20.d.ts:21:22 -
  error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

21 export declare class Download20Module {
                        ~~~~~~~~~~~~~~~~
```

## covalentcore-ngcc
```sh
Compiling @covalent/core/common : module as esm5
Compiling @covalent/core : module as esm5

ERROR in Tried to overwrite /home/circleci/repo/node_modules/@covalent/core/common/forms/auto-trim/auto-trim.directive.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
```

## delonform-ngcc
```sh
Compiling @delon/form : module as esm5

ERROR in ../../node_modules/@delon/form/src/widget.d.ts:35:40 -
  error TS2314: Generic type 'Widget<T, UIT>' requires 2 type argument(s).

35     static ngBaseDef: ɵngcc0.ɵɵBaseDef<Widget>;
                                          ~~~~~~
```

## harborui-ngcc
```sh
ERROR in The target entry-point "@harbor/ui" has missing dependencies:
  - @nguniversal/express-engine/tokens
```

## kendo-ui-ngcc
```sh
Compiling @progress/kendo-angular-dropdowns : module as esm5

ERROR in Unsupported binary operator: InKeyword
```

## mobx-angular-ngcc
```sh
1) workspace-project App should display welcome message
  - Failed: No element found using locator: By(css selector, app-root h1)
  - Expected [ Entry({ level: SEVERE, message: 'http://localhost:4200/vendor.js 10542:18 "ERROR" TypeError: Cannot read property 'component' of undefined
      at MobxAutorunDirective.push.../../node_modules/mobx-angular/__ivy_ngcc__/dist/directives/mobx-autorun.directive.js.MobxAutorunDirective.autoDetect (http://localhost:4200/vendor.js:42003:38)
      at MobxAutorunDirective.push.../../node_modules/mobx-angular/__ivy_ngcc__/dist/directives/mobx-autorun.directive.js.MobxAutorunDirective.ngOnInit (http://localhost:4200/vendor.js:41996:14)
      at callHook (http://localhost:4200/vendor.js:12238:18)
      at callHooks (http://localhost:4200/vendor.js:12208:17)
      at executeInitAndCheckHooks (http://localhost:4200/vendor.js:12161:9)
      at refreshView (http://localhost:4200/vendor.js:15314:21)
      at refreshComponent (http://localhost:4200/vendor.js:16285:9)
      at refreshChildComponents (http://localhost:4200/vendor.js:15107:9)
      at refreshView (http://localhost:4200/vendor.js:15345:13)
      at renderComponentOrTemplate (http://localhost:4200/vendor.js:15389:9)', timestamp: 1572517749630, type: '' }) ] not to contain <jasmine.objectContaining(Object({ level: SEVERE }))>.
```

## mydatepicker-ngcc
```sh
ERROR in ../../node_modules/mydatepicker/dist/my-date-picker.component.d.ts:1:81 -
  error TS2724: Module '"../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { EventEmitter, OnChanges, SimpleChanges, ElementRef, ChangeDetectorRef, Renderer, OnDestroy } from "@angular/core";
                                                                                  ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```

## nativescript-angular-ngcc
```sh
ERROR in ../../node_modules/nativescript-angular/dom-adapter.d.ts:2:10 -
  error TS2305: Module '"../@angular/platform-browser/platform-browser"' has no exported member 'ɵDomAdapter'.

2 import { ɵDomAdapter } from "@angular/platform-browser";
           ~~~~~~~~~~~
```

## nebularauth-ngcc
```sh
Compiling @nebular/theme : module as esm5

ERROR in ../../node_modules/@nebular/theme/components/datepicker/datepicker.component.d.ts:176:40 -
  error TS2314: Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s).

176     static ngBaseDef: ɵngcc0.ɵɵBaseDef<NbBasePicker>;
                                           ~~~~~~~~~~~~
```

## nebulardate-fns-ngcc
```sh
Compiling @nebular/theme : module as esm5

ERROR in ../../node_modules/@nebular/theme/components/datepicker/datepicker.component.d.ts:176:40 -
  error TS2314: Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s).

176     static ngBaseDef: ɵngcc0.ɵɵBaseDef<NbBasePicker>;
                                           ~~~~~~~~~~~~
```

## nebulareva-icons-ngcc
```sh
Compiling @nebular/theme : module as esm5

ERROR in ../../node_modules/@nebular/theme/components/datepicker/datepicker.component.d.ts:176:40 -
  error TS2314: Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s).

176     static ngBaseDef: ɵngcc0.ɵɵBaseDef<NbBasePicker>;
                                           ~~~~~~~~~~~~
```

## nebularmoment-ngcc
```sh
Compiling @nebular/theme : module as esm5

ERROR in ../../node_modules/@nebular/theme/components/datepicker/datepicker.component.d.ts:176:40 -
  error TS2314: Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s).

176     static ngBaseDef: ɵngcc0.ɵɵBaseDef<NbBasePicker>;
                                           ~~~~~~~~~~~~
```

## nebulartheme-ngcc
```sh
Compiling @nebular/theme : module as esm5

ERROR in ../../node_modules/@nebular/theme/components/datepicker/datepicker.component.d.ts:176:40 -
  error TS2314: Generic type 'NbBasePicker<D, T, P>' requires 3 type argument(s).

176     static ngBaseDef: ɵngcc0.ɵɵBaseDef<NbBasePicker>;
                                           ~~~~~~~~~~~~
```

## ng-bootstrapng-bootstrap-ngcc
```sh
1) workspace-project App should display welcome message
  - Failed: Angular could not be found on the page http://localhost:4200/. If this is not an Angular application, you may need to turn off waiting for Angular.
                            Please see https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  - Expected [ Entry({ level: SEVERE, message: 'http://localhost:4200/vendor.js 37668:14 Uncaught Error: It looks like your application or one of its depen…gular/localize/init';` to your polyfills.ts file)', timestamp: 1571389797166, type: '' }) ] not to contain <jasmine.objectContaining(Object({ level: SEVERE }))>.
```

## ng-pick-datetime-ngcc
```sh
Compiling ng-pick-datetime : module as esm5

ERROR in ../../node_modules/ng-pick-datetime/date-time/date-time.class.d.ts:50:40 -
  error TS2314: Generic type 'OwlDateTime<T>' requires 1 type argument(s).

50     static ngBaseDef: ɵngcc0.ɵɵBaseDef<OwlDateTime>;
                                          ~~~~~~~~~~~
```

## ng2-completer-ngcc
```sh
Compiling ng2-completer : module as esm5

ERROR in ../../node_modules/ng2-completer/src/directives/ctr-row.d.ts:1:22 -
  error TS2724: Module '"../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ElementRef, Renderer, OnDestroy } from "@angular/core";
                       ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```

## ng2-dragula-ngcc
```sh
1) workspace-project App should display welcome message
  - Failed: Angular could not be found on the page http://localhost:4200/. If this is not an Angular application, you may need to turn off waiting for Angular.
                            Please see https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  - Expected [ Entry({ level: SEVERE, message: 'http://localhost:4200/vendor.js 40358:24 Uncaught ReferenceError: global is not defined', timestamp: 1571389850818, type: '' }) ] not to contain <jasmine.objectContaining(Object({ level: SEVERE }))>.
```

## ng2-file-upload-ngcc
```sh
Compiling ng2-file-upload : module as esm5

ERROR in ../../node_modules/ng2-file-upload/file-upload/file-upload.module.d.ts:1:22 -
  error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

1 export declare class FileUploadModule {
                       ~~~~~~~~~~~~~~~~
```

## ng2-material-dropdown-ngcc
```sh
Compiling ng2-material-dropdown : module as esm5

ERROR in ../../node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:1:10 -
  error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { Renderer, ElementRef, OnDestroy } from '@angular/core';
           ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

../../node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:1:22 -
  error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ElementRef, Renderer, QueryList } from '@angular/core';
                       ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```

## nguniversalaspnetcore-engine-ngcc
```sh
Compiling @nguniversal/aspnetcore-engine : module as esm5

ERROR in /home/circleci/repo/node_modules/@nguniversal/aspnetcore-engine/__ivy_ngcc__/fesm5/aspnetcore-engine.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/repo/node_modules/@nguniversal/aspnetcore-engine/__ivy_ngcc__/fesm5'
```

## nguniversalexpress-engine-ngcc
```sh
Compiling @nguniversal/express-engine : module as esm5

ERROR in /home/circleci/repo/node_modules/@nguniversal/express-engine/__ivy_ngcc__/fesm5/express-engine.js
Module not found: Error: Can't resolve 'fs' in '/home/circleci/repo/node_modules/@nguniversal/express-engine/__ivy_ngcc__/fesm5'
```

## ngx-chips-ngcc
```sh
Compiling ng2-material-dropdown : module as esm5

ERROR in ../../node_modules/ng2-material-dropdown/src/modules/components/menu-item/ng2-menu-item.d.ts:1:10 -
  error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { Renderer, ElementRef, OnDestroy } from '@angular/core';
           ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.

../../node_modules/ng2-material-dropdown/src/modules/components/menu/ng2-dropdown-menu.d.ts:1:22 -
  error TS2724: Module '"../../../../../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

1 import { ElementRef, Renderer, QueryList } from '@angular/core';
                       ~~~~~~~~

  ../../node_modules/@angular/core/core.d.ts:5388:31
    5388 export declare abstract class Renderer2 {
                                       ~~~~~~~~~
    'Renderer2' is declared here.
```

## ngx-formlymaterial-ngcc
```sh
1) workspace-project App should display welcome message
  - Failed: Angular could not be found on the page http://localhost:4200/. If this is not an Angular application, you may need to turn off waiting for Angular.
                            Please see https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  - Expected [ Entry({ level: SEVERE, message: 'http://localhost:4200/vendor.js 83413:17 Uncaught TypeError: Cannot set property 'ɵfac' of undefined', timestamp: 1572366624091, type: '' }) ] not to contain <jasmine.objectContaining(Object({ level: SEVERE }))>.
```

## ngx-simple-modal-ngcc
```sh
1) workspace-project App should display welcome message
  - Failed: Angular could not be found on the page http://localhost:4200/. If this is not an Angular application, you may need to turn off waiting for Angular.
                            Please see https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  - Expected [ Entry({ level: SEVERE, message: 'http://localhost:4200/vendor.js 71778:22 Uncaught ReferenceError: exports is not defined', timestamp: 1572284235196, type: '' }) ] not to contain <jasmine.objectContaining(Object({ level: SEVERE }))>.
```

## uirouterangular-ngcc
```sh
1) ui-router/angular should navigate to each view
  - Expected '' to equal 'lazy1 works!'.
  - Expected [ Entry({ level: SEVERE, message: 'http://localhost:4200/vendor.js 10542:18 "ERROR" TypeError: Cannot read property 'createComponent' of undefined
      at UIView.push.../../node_modules/@uirouter/angular/__ivy_ngcc__/lib/directives/uiView.js.UIView._applyUpdatedConfig (http://localhost:4200/vendor.js:47413:52)
      at UIView.push.../../node_modules/@uirouter/angular/__ivy_ngcc__/lib/directives/uiView.js.UIView._viewConfigUpdated (http://localhost:4200/vendor.js:47399:14)
      at configureUIView (http://localhost:4200/vendor.js:59508:30)
      at Array.forEach (<anonymous>)
      at ViewService.push.../../node_modules/@uirouter/core/__ivy_ngcc__/lib-esm/view/view.js.ViewService.sync (http://localhost:4200/vendor.js:59516:22)
      at ViewService.push.../../node_modules/@uirouter/core/__ivy_ngcc__/lib-esm/view/view.js.ViewService.registerUIView (http://localhost:4200/vendor.js:59543:14)
      at UIView.push.../../node_modules/@uirouter/angular/__ivy_ngcc__/lib/directives/uiView.js.UIView.ngOnInit (http://localhost:4200/vendor.js:47275:53)
      at callHook (http://localhost:4200/vendor.js:12238:18)
      at callHooks (http://localhost:4200/vendor.js:12208:17)
      at executeInitAndCheckHooks (http://localhost:4200/vendor.js:12161:9)', timestamp: 1572518064424, type: '' }) ] not to contain <jasmine.objectContaining(Object({ level: SEVERE }))>.
```

## uirouterangular-hybrid-ngcc
```sh
Compiling @uirouter/angular-hybrid : module as esm5

ERROR in Symbol UIRouterModule declared in /home/circleci/repo/node_modules/@uirouter/angular/lib/uiRouterNgModule.d.ts is not exported from @uirouter/angular-hybrid (import into /home/circleci/repo/projects/uirouterangular-hybrid-ngcc/src/app/child.module.ts)
```

</details>

**Comment by mgechev** [comment]
Few updates:

- Reached out to @valorkin for `ng2-dracula` & `ng2-file-upload`
- Waiting for @tsvetomir to come back to me. From our latest conversation, seems like the runtime errors in Kendo have been taken care of
- @crisbeto is working on a fix that will fix `@nebular/theme` and transitively 4 more `@nebular/*`packages
- @adamkleingit is working on a fix of `mobx-angular`, which will transitively fix `angular-tree-component`

**Comment by gkalpak** [comment]
Since we are now using [this spreadsheet][1] for tracking, I no longer intend to keep this issue up-to-date.

[1]: https://docs.google.com/spreadsheets/d/1brJHrqGYGGD4HRsFudGW6CynHHX34Zf8H31qD7wjPac/edit#gid=0
